### ISSUE TITLE
setup_class running multiple times

### ISSUE THREAD

**Issue by kksure** [pytest-dev/pytest-rerunfailures#7]
Hi,

we have a class that looks like below:

========================
def setup_class
      raises exception

def test_one
     pass

def test_two
     pass

def test_three
     pass

=========================

when the setup fails we expect all the tests to fail. However after I installed this plugin, the setup_class is run before every test.

Is there a way to suppress the rerun of setup with every test if the setup_class fails.

This means even if I don't use --reruns option, this changes the default behavior of py.test.

**Comment by florianpilz** [comment]
Hi kksure! We (gocept) have accepted the ownership of pytest-rerunfailures and are the new maintainers.

Since we have limited resources ourselves, I have to ask for your assistance. It would be of great help if you could create a test for pytest-rerunfailures, which repeatedly fails due to your problem. That would help to implement a solution tremendously. Maybe you could implement the test on a branch.

**Comment by florianpilz** [comment]
@kksure: In the latest release the core logic was rewritten by @davehunt. Maybe that fixed your issues, bother to try again?

From what I have seen, any test is rerun if setup, the test itself or teardown failed. I guess in your case the same setup report is given to all tests, which reruns them all. So I guess it still misbehaves.

**Comment by florianpilz** [comment]
@kksure: Ich just added a test concerning test classes using `setup_class`. If `--reruns` is involved the expected behavior is to rerun every test of that class. What did you mean by "changes the behavior of pytest even when used with `--reruns=0`"?

In any case, please extend / adjust the test cases concerning classes, so I can reproduce your problem.

**Comment by florianpilz** [comment]
I think this problem is not present anymore. As far as I remember, the code now correctly handles a setup failure.
