### ISSUE TITLE
Rerun , only when the Pytest fixture or setup class is failed

### ISSUE THREAD

**Issue by sourcecode14** [pytest-dev/pytest-rerunfailures#82]
Hi,

I would like to only rerun the test when the pytest fixture added inside conftest file is failed . I am not concerned about failures in actual test. I am concerned about the failures happening in pytest fixtures . Hence , I would like to rerun only when the pytest fixture or setup class is failed. 

Is it possible through rerun failure plugin

**Comment by lytviakot** [comment]
Hi, @sagardaine 

Did you find answer to your question?
I'm new to python and pytest and can't find the way to rerun only failed setup/teardown.

**Comment by kousu** [comment]
I would like to know this too. I also have flaky fixtures.

If your fixtures error with specific exceptions you know, maybe #58 would help you. Unfortunately it's not written yet.

I switched one of my projects to [flaky](https://github.com/box/flaky#dont-rerun-certain-types-of-failures) because they support that. Maybe you could use that in the meantime?

**Comment by ls-sergii-buchovskyi** [comment]
Same here, cannot rerun test if it errors on setup on teardown...

**Comment by sallner** [comment]
@lytviakot @sourcecode14 It is now possible to specify a `--only-rerun` (https://github.com/pytest-dev/pytest-rerunfailures/pull/113)  option, which can be used in combination with a special exception raised during setup and teardown to rerun the test in this case. Please try this. I will close this issue for now. In case you need it further, please open it again.
